# -*- coding: utf-8 -*-
"""loop-rec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/1nf1n1tee/0b10591117efda4e711d9c10bdeaf294/loop-rec.ipynb
"""

def loop(arr,p=0,i=0):
  if p == 0:
    if i == len(arr):
      return
    else:
      print(arr[i])
      return loop(arr,i+1)

  if i < len(arr):

    print(arr[len(arr)-1-i])
    return loop(arr,-1,i+1)

arr = [10,20,30,40,50]
loop(arr,1)