# -*- coding: utf-8 -*-
"""loop rec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTS4FWO5BpeG565mw4yR7iYeyYcQ2fka
"""

def merge_max_div(arr):
  if len(arr) == 1:
    return arr

  mid = len(arr)//2
  left = merge_max_div(arr[:mid])
  right = merge_max_div(arr[mid:])
  return merge_max_con(left,right)

def merge_max_con(left,right):
  if left > right:
    return left
  return right

arr = [60,5,6,6,10,11]
print(merge_max_div(arr))